substitutions:
  devicename: climate
  upper_devicename: "Climate"

esphome:
  name: $devicename
  friendly_name: ${upper_devicename}
  comment: $upper_devicename faikin
#  name_add_mac_suffix: true
  project:
    name: Daikin.S21_climate
    version: "faikin-s3-1.0"
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
    version: 2.0.6

external_components:
  - source: github://joshbenner/esphome-daikin-s21@main
    components: [ daikin_s21 ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: "12345678"

# Enable logging
logger:
  baud_rate: 0 # disable serial logging;
#  hardware_uart: USB_SERIAL_JTAG
#  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:

#web_server:

uart:
  - id: s21_uart
    tx_pin:
      number: GPIO48
      inverted: true
    rx_pin:
      number: GPIO34
      inverted: true
    baud_rate: 2400
    data_bits: 8
    parity: EVEN
    stop_bits: 2
#    debug:
#      direction: BOTH

# The base UART communication hub.
daikin_s21:
  tx_uart: s21_uart
  rx_uart: s21_uart
#  debug_protocol: true

climate:
  - name: Daikin
    platform: daikin_s21
    visual:
      temperature_step: 1.0
    # Optional HA sensor used to alter setpoint.
    room_temperature_sensor: room_temp  # See homeassistant sensor below

# optional binary sensor to monitor serial connection:
binary_sensor:
  - platform: status
    name: "Status"

#bluetooth_proxy:
#  active: true

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic
  - platform: restart
    name: "Restart"

#esp32_ble_tracker:
#  scan_parameters:
#    interval: 1100ms
#    window: 1100ms
#    active: true

interval:
  - interval: 60s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - light.turn_on:
              id: s3_wled
              brightness: 10%
              color_brightness: 50%
              red: 100%
              blue: 100%
              green: 98%
        else:
          - light.turn_on:
              id: s3_wled
              flash_length : 1s
              brightness: 50%
              color_brightness: 50%
              red: 100%

light:
  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: GPIO47
    num_leds: 3
    rgb_order: GRB
    rmt_channel: 0
    id: s3_wled
    name: "RGB LED"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1

# Optional additional sensors.
  - platform: daikin_s21
    inside_temperature:
      name: Daikin Inside Temperature
    outside_temperature:
      name: Daikin Outside Temperature
    coil_temperature:
      name: Daikin Coil Temperature
    fan_speed:
      name: Daikin Fan Speed
  - platform: homeassistant
    id: room_temp
    entity_id: sensor.temperature_158d000111fe66
    unit_of_measurement: °C

  - platform: internal_temperature
    name: "Internal Temperature"

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"

time:
  - platform: homeassistant
    id: homeassistant_time
