substitutions:
  devicename: fan-taiseia
  upper_devicename: "Fan TaiSEIA"

esphome:
  name: $devicename
  friendly_name: ${upper_devicename}
  comment: $upper_devicename
  name_add_mac_suffix: true
  project:
    name: TaiSEIA.climate
    version: "1.0"

external_components:
  - source: github://tsunglung/taixia@master
    components: [ taixia ]

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  reboot_timeout: 0s
  ap:
    password: "admin1234"
    ap_timeout: 30s

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  - platform: esphome

uart:
  id: uart_taixia
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600

binary_sensor:
  - platform: status
    name: "Status"

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic
  - platform: restart
    name: "Restart"

fan:
  - platform: taixia
    name: Fan
    speed: true
    speed_count: 2

number:
  - platform: taixia
    type: electricfan
    off_timer:
      name: "Off Timer"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1

  - platform: internal_temperature
    name: "Internal Temperature"

switch:
  - platform: taixia
    type: electricfan
    power:
      name: "Power Switch"

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
  - platform: taixia
    sa_id:
      name: "SA ID"
      id: sa_id
    brand:
      name: "SA Brand"
    model:
      name: "SA Model"
    version:
      name: "SA Version"
    services:
      name: "SA Services"

taixia:
  sa_id: 15

time:
  - platform: homeassistant
    id: homeassistant_time
