substitutions:
  devicename: erv-taiseia-atom-lite
  upper_devicename: "ERV KPI-H"

esphome:
  name: $devicename
  friendly_name: ${upper_devicename}
  comment: $upper_devicename for Hitachi KPI-152Y
  name_add_mac_suffix: true
  project:
    name: TaiSEIA.erv
    version: "1.0"

esp32:
  board: nodemcu-32s
  variant: esp32
  framework:
    type: esp-idf

external_components:
  - source: github://tsunglung/taixia@master
    components: [ taixia ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: "12345678"

captive_portal:

# Enable logging
logger:
  baud_rate: 0 # disable serial logging;
#  hardware_uart: USB_SERIAL_JTAG
#  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:
  - platform: esphome

# web_server:

uart:
  id: uart_taixia
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 9600
  debug:
    direction: BOTH

# optional binary sensor to monitor serial connection:
binary_sensor:
  - platform: status
    name: "Status"
  - platform: taixia
    type: erv
    filter_notify:
      name: "Filter Notify"
    front_filter_notify:
      name: "Front Filter Notify"
    pm25_filter_notify:
      name: "PM2.5 Filter Notify"

#bluetooth_proxy:
#  active: true

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic
  - platform: restart
    name: "Restart"
  - platform: taixia
    type: erv
    get_info:
      name: "Get Info"
    filter_clean_notify:
      name: "Reset Filter Notify"
    front_filter_notify:
      name: "Rest Front Filter Notify"
    pm25_filter_notify:
      name: "Rest PM2.5 Filter Notify"

light:
  - platform: esp32_rmt_led_strip
    id: esp32_rgb_led
    name: Status RGB LED
    rgb_order: RGB
    pin: GPIO27
    num_leds: 1
    icon: mdi:led-outline
    entity_category: config
    restore_mode: ALWAYS_OFF
    chipset: ws2812

number:
  - platform: taixia
    type: erv
    fan_level:
      name: "Fan Level"
      min_value: 2
      max_value: 4

select:
  - platform: taixia
    type: erv
    ventilate_mode:
      name: "Ventilate Mode"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1

  - platform: taixia
    type: erv
    temperature_indoor:
      name: "Temperature Indoor"
    model_type:
      name: "Model Type"
    error_code:
      name: "Error Code"

switch:
  - platform: taixia
    type: erv
    immediate_update: false
    power:
      name: "Power Switch"

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
  - platform: taixia
    sa_id:
      name: "SA ID"
      id: sa_id
    brand:
      name: "SA Brand"
    model:
      name: "SA Model"
    version:
      name: "SA Version"
    services:
      name: "SA Services"

taixia:
   sa_id: 14

time:
  - platform: homeassistant
    id: homeassistant_time
